apiVersion: v1
kind: Service
metadata:
  name: community-autopilot
  namespace: benni-os
spec:
  selector:
    app: community-autopilot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
